apiVersion: apps/v1beta2       #必选，版本号，例如v1
kind: Deployment       #必选，Pod
metadata:       #必选，元数据
  name: semf      #必选，Pod名称
  namespace: semf    #必选，Pod所属的命名空间
spec:
    replicas: 1
    selector:
      matchLabels:
        app: semf
    template:
      metadata:
        labels:
          app: semf
      spec:         #必选，Pod中容器的详细定义
        containers:      #必选，Pod中容器列表
        - name: semf      #必选，容器名称
          image: registry.company.com:8500/company/semf:v1.1.2    #必选，容器的镜像名称
          imagePullPolicy: Always #获取镜像的策略 Always表示下载镜像 IfnotPresent表示优先使用本地镜像，否则下载镜像，Nerver表示仅使用本地镜像
          ports:       #需要暴露的端口库号列表
          - name: semfport     #端口号名称
            containerPort: 8000   #容器需要监听的端口号
            # hostPort: int    #容器所在主机需要监听的端口号，默认与Container相同
            protocol: TCP     #端口协议，支持TCP和UDP，默认TCP
          command: ['uwsgi']
          args: ['--ini', './uwsgi.ini']
