apiVersion: v1
kind: Service
metadata:
  name: semf
  labels:
    service: semf
spec:
  type: ClusterIP
  ports:
  - name: semf
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: semf